Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: Z:/Coding Classes/Python Text Adventures/wwif/students/simone/kjf dlscvniuekdfs.py 
Player 1, enter a word bubble
>>> 
 RESTART: Z:/Coding Classes/Python Text Adventures/wwif/students/simone/kjf dlscvniuekdfs.py 
Traceback (most recent call last):
  File "Z:/Coding Classes/Python Text Adventures/wwif/students/simone/kjf dlscvniuekdfs.py", line 4, in <module>
    getpass,getpass("Player 1, enter a word")
TypeError: 'module' object is not callable
>>> 
 RESTART: Z:/Coding Classes/Python Text Adventures/wwif/students/simone/kjf dlscvniuekdfs.py 

Warning (from warnings module):
  File "C:\Users\wwclc\AppData\Local\Programs\Python\Python35\lib\getpass.py", line 101
    return fallback_getpass(prompt, stream)
GetPassWarning: Can not control echo on the terminal.
Warning: Password input may be echoed.
Player 1, enter a word
